### ISSUE TITLE
Everything broke

### ISSUE THREAD

**Issue by edorgeville** [jonathangerbaud/Klyph#2]
The app won't load anything : no newfeed, no timeline, no posts. You can get notifications, but if you click on those you get an error.

**Comment by jonathangerbaud** [comment]
Well, that's why I stopped developing using Facebook platform: random errors. I just checked, just to be sure, and this is what I get when trying to get the news feed: "An unknown error has occurred". Thank you Facebook, it's a very useful error. 

You can note that I haven't modified the code since December and it was working perfectly well until a few days ago. I receive a lot of bug reports from klyph's users about this newsfeed problem, but I didn't make any update since December.

You can send a bug report on the Facebook developers platform.

**Comment by edorgeville** [comment]
I understand your hate against Facebook and its API. That's a shame those guys don't give a fuck about the devs.

**Comment by geeknizer** [comment]
Any error codes?

**Comment by edorgeville** [comment]
Nope. only "An unknown error has occurred".
